//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsExamen324.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PERSONAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PERSONAS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PERSONAS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PERSONASAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string INSERT(string ci, string nombrec, string fechanac, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> INSERTAsync(string ci, string nombrec, string fechanac, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UPDATE(string idCI, string ci, string nombrec, string fechanac, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UPDATEAsync(string idCI, string ci, string nombrec, string fechanac, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DELETE(string idCI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DELETEAsync(string idCI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsExamen324.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsExamen324.ServiceReference1.WebService1Soap>, WindowsFormsExamen324.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet PERSONAS() {
            return base.Channel.PERSONAS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PERSONASAsync() {
            return base.Channel.PERSONASAsync();
        }
        
        public string INSERT(string ci, string nombrec, string fechanac, string departamento) {
            return base.Channel.INSERT(ci, nombrec, fechanac, departamento);
        }
        
        public System.Threading.Tasks.Task<string> INSERTAsync(string ci, string nombrec, string fechanac, string departamento) {
            return base.Channel.INSERTAsync(ci, nombrec, fechanac, departamento);
        }
        
        public string UPDATE(string idCI, string ci, string nombrec, string fechanac, string departamento) {
            return base.Channel.UPDATE(idCI, ci, nombrec, fechanac, departamento);
        }
        
        public System.Threading.Tasks.Task<string> UPDATEAsync(string idCI, string ci, string nombrec, string fechanac, string departamento) {
            return base.Channel.UPDATEAsync(idCI, ci, nombrec, fechanac, departamento);
        }
        
        public string DELETE(string idCI) {
            return base.Channel.DELETE(idCI);
        }
        
        public System.Threading.Tasks.Task<string> DELETEAsync(string idCI) {
            return base.Channel.DELETEAsync(idCI);
        }
    }
}
